name: PR Checks
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 1
      - uses: ./.github/actions/spell-check
        name: Spell Check
  broken-link-check:
    needs: spell-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 1
          submodules: true
      - uses: ./.github/actions/link-check
        name: Link Check
        env:
          HUGO_OPTIONS: "-b http://localhost:1313/developer" #"--buildDrafts"
          MUFFET_OPTIONS: "-e 'https?' --exclude='/developer/get-workshop'" # Excludes external links
  lighthouse-checks:
    needs: broken-link-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jakepartusch/wait-for-netlify-action@v1
        name: wait_for_deploy_preview
        id: netlify
        with:
          site_name: tanzu-dev-portal
      - uses: treosh/lighthouse-ci-action@v7
        name: lighthouse
        with:
          temporaryPublicStorage: true
          configPath: ./lighthouserc.yml
          urls: |
            ${{ steps.netlify.outputs.url }}/developer/
