name: Get Latest tanzu-talk Episodes
on:
  schedule:
    - cron: "0 16 * * 2,3,5"
  workflow_dispatch:
jobs:
  get-episodes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 1
          token: ${{ secrets.PA_TOKEN }}
      - name: Checkout tanzu-talk Branch
        run: |
          git checkout -B tanzu-talk
          if git ls-remote --heads --exit-code https://github.com/vmware-tanzu/tanzu-dev-portal.git tanzu-talk;then git fetch && \
          git branch --set-upstream-to=origin/tanzu-talk tanzu-talk && git pull; else \
          git push --set-upstream origin tanzu-talk; fi
      - uses: ./.github/actions/youtube-episodes
        name: Get Latest tanzu-talk Episodes (creates local changes)
        env:
          API_KEY: ${{ secrets.YT_API_KEY }}
          PLAYLIST_ID: "PLAdzTan_eSPRNuA52_34wh5VTBC-0Rz7U"
          EPISODES_PATH: "content/tv/talk/"
          IMG_PATH_PREFIX: "static/"
          IMAGES_REL_PATH: "images/tv/episodes/talk/"
          TEMPLATE_FILE: ".github/actions/youtube-episodes/src/template.md"
          TITLE_PREFIX: "Tanzu Talk"
          TITLE_SUFFIX: ", "
      - name: Cleanup tanzu-talk branch on failure
        if: ${{ failure() }}
        run: |
          git push origin --delete tanzu-talk
      - name: Check for modified files
        id: git-check
        run: |
          git add --all
          echo ::set-output name=modified::$(if git diff --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Commit files
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
          git push
      - name: Cleanup tanzu-talk branch
        if: steps.git-check.outputs.modified == 'false'
        run: |
          git push origin --delete tanzu-talk
