name: Get Latest TGIK Episodes
on:
  schedule:
    - cron: "0 16 * * 2,3,5"
  workflow_dispatch:
jobs:
  get-episodes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 1
          token: ${{ secrets.PA_TOKEN }}
      - name: Checkout TGIK Branch
        run: |
          git checkout -B youtube-tgik
          if git ls-remote --heads --exit-code https://github.com/vmware-tanzu/tanzu-dev-portal.git youtube-tgik;then git fetch && \
          git branch --set-upstream-to=origin/youtube-tgik youtube-tgik && git pull; else \
          git push --set-upstream origin youtube-tgik; fi
      - uses: ./.github/actions/youtube-episodes
        name: Get Latest TGIK Episodes (creates local changes)
        env:
          API_KEY: ${{ secrets.YT_API_KEY }}
          PLAYLIST_ID: "PL7bmigfV0EqQzxcNpmcdTJ9eFRPBe-iZa"
          EPISODES_PATH: "content/tv/tgik/"
          IMG_PATH_PREFIX: "images/"
          TEMPLATE_FILE: ".github/actions/youtube-episodes/src/template.md"
      - name: Check for modified files
        id: git-check
        run: |
          git add --all
          echo ::set-output name=modified::$(if git diff --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Commit files
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
          git push
      - name: Cleanup tgik branch
        if: steps.git-check.outputs.modified == 'false'
        run: |
          git push origin --delete youtube-tgik
